export interface City {
  slug: string;
  name: string;
  region: string;
  department: string;
  population: string;
  description: string;
  localBusinesses: string;
  mapCenter: { lat: number; lng: number };
  keyNeighborhoods: string[];
  typicalSearches: string[];
}

export const CITIES: City[] = [
  {
    slug: 'paris',
    name: 'Paris',
    region: 'Île-de-France',
    department: 'Paris (75)',
    population: '2,1 millions',
    description: 'Capitale française et plus grande métropole du pays, Paris concentre une densité exceptionnelle de commerces et de services. La concurrence sur Google Maps y est féroce : se démarquer exige une stratégie SEO locale pointue.',
    localBusinesses: '400 000+',
    mapCenter: { lat: 48.8566, lng: 2.3522 },
    keyNeighborhoods: ['Le Marais', 'Montmartre', 'Saint-Germain', 'Bastille', 'Opéra'],
    typicalSearches: ['restaurant paris', 'dentiste paris 16', 'plombier paris 11', 'coiffeur paris 9'],
  },
  {
    slug: 'lyon',
    name: 'Lyon',
    region: 'Auvergne-Rhône-Alpes',
    department: 'Rhône (69)',
    population: '520 000',
    description: 'Deuxième pôle économique de France, Lyon est une ville dynamique où les commerces de proximité se disputent les premières places sur Google Maps. De la Presqu\'île à la Part-Dieu, chaque quartier a ses spécificités.',
    localBusinesses: '85 000+',
    mapCenter: { lat: 45.764, lng: 4.8357 },
    keyNeighborhoods: ['Presqu\'île', 'Part-Dieu', 'Vieux Lyon', 'Confluence', 'Croix-Rousse'],
    typicalSearches: ['restaurant lyon', 'boulangerie lyon 6', 'garage lyon 3', 'avocat lyon'],
  },
  {
    slug: 'marseille',
    name: 'Marseille',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: 'Bouches-du-Rhône (13)',
    population: '870 000',
    description: 'Deuxième ville de France par sa population, Marseille est un carrefour méditerranéen vibrant. Du Vieux-Port à la Joliette, les entreprises locales doivent optimiser leur présence digitale pour capter les habitants et les touristes.',
    localBusinesses: '120 000+',
    mapCenter: { lat: 43.2965, lng: 5.3698 },
    keyNeighborhoods: ['Vieux-Port', 'La Joliette', 'Le Panier', 'Castellane', 'La Canebière'],
    typicalSearches: ['restaurant marseille', 'plombier marseille', 'dentiste marseille 8', 'coiffeur marseille'],
  },
  {
    slug: 'toulouse',
    name: 'Toulouse',
    region: 'Occitanie',
    department: 'Haute-Garonne (31)',
    population: '500 000',
    description: 'La Ville Rose est l\'une des métropoles les plus dynamiques de France. Avec son écosystème aéronautique et sa population étudiante, Toulouse offre un marché local en pleine croissance pour les entreprises visibles sur Google Maps.',
    localBusinesses: '75 000+',
    mapCenter: { lat: 43.6047, lng: 1.4442 },
    keyNeighborhoods: ['Capitole', 'Saint-Cyprien', 'Carmes', 'Compans-Caffarelli', 'Rangueil'],
    typicalSearches: ['restaurant toulouse', 'garage automobile toulouse', 'dentiste toulouse centre', 'avocat toulouse'],
  },
  {
    slug: 'nice',
    name: 'Nice',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: 'Alpes-Maritimes (06)',
    population: '340 000',
    description: 'Capitale de la Côte d\'Azur, Nice attire touristes et résidents toute l\'année. Les commerces locaux font face à une double concurrence : satisfaire les habitants et capter les millions de visiteurs annuels via Google Maps.',
    localBusinesses: '55 000+',
    mapCenter: { lat: 43.7102, lng: 7.262 },
    keyNeighborhoods: ['Vieux-Nice', 'Cimiez', 'Libération', 'Jean Médecin', 'Port'],
    typicalSearches: ['restaurant nice', 'dentiste nice', 'coiffeur nice centre', 'plombier nice'],
  },
  {
    slug: 'nantes',
    name: 'Nantes',
    region: 'Pays de la Loire',
    department: 'Loire-Atlantique (44)',
    population: '320 000',
    description: 'Nantes est une métropole en plein essor, régulièrement classée parmi les villes où il fait bon vivre. Les entreprises locales y trouvent un marché porteur, à condition d\'être bien positionnées sur Google Maps.',
    localBusinesses: '50 000+',
    mapCenter: { lat: 47.2184, lng: -1.5536 },
    keyNeighborhoods: ['Centre-ville', 'Île de Nantes', 'Talensac', 'Graslin', 'Erdre'],
    typicalSearches: ['restaurant nantes', 'plombier nantes', 'dentiste nantes centre', 'boulangerie nantes'],
  },
  {
    slug: 'strasbourg',
    name: 'Strasbourg',
    region: 'Grand Est',
    department: 'Bas-Rhin (67)',
    population: '290 000',
    description: 'Capitale européenne et ville au patrimoine UNESCO, Strasbourg mêle attractivité touristique et dynamisme économique. Les commerces locaux doivent se démarquer dans un environnement concurrentiel unique.',
    localBusinesses: '45 000+',
    mapCenter: { lat: 48.5734, lng: 7.7521 },
    keyNeighborhoods: ['Grande Île', 'Petite France', 'Krutenau', 'Neudorf', 'Orangerie'],
    typicalSearches: ['restaurant strasbourg', 'dentiste strasbourg', 'garage strasbourg', 'coiffeur strasbourg'],
  },
  {
    slug: 'montpellier',
    name: 'Montpellier',
    region: 'Occitanie',
    department: 'Hérault (34)',
    population: '300 000',
    description: 'Montpellier est l\'une des villes françaises à la croissance démographique la plus rapide. Cette expansion crée des opportunités immenses pour les entreprises locales prêtes à dominer Google Maps.',
    localBusinesses: '48 000+',
    mapCenter: { lat: 43.6108, lng: 3.8767 },
    keyNeighborhoods: ['Écusson', 'Antigone', 'Port Marianne', 'Beaux-Arts', 'Les Arceaux'],
    typicalSearches: ['restaurant montpellier', 'dentiste montpellier', 'plombier montpellier', 'avocat montpellier'],
  },
  {
    slug: 'bordeaux',
    name: 'Bordeaux',
    region: 'Nouvelle-Aquitaine',
    department: 'Gironde (33)',
    population: '260 000',
    description: 'Bordeaux a connu une transformation spectaculaire ces dernières années. La métropole attire de nouveaux habitants et entreprises, rendant la visibilité locale sur Google Maps plus stratégique que jamais.',
    localBusinesses: '45 000+',
    mapCenter: { lat: 44.8378, lng: -0.5792 },
    keyNeighborhoods: ['Saint-Pierre', 'Chartrons', 'Saint-Michel', 'Bastide', 'Mériadeck'],
    typicalSearches: ['restaurant bordeaux', 'dentiste bordeaux', 'plombier bordeaux', 'garage bordeaux'],
  },
  {
    slug: 'lille',
    name: 'Lille',
    region: 'Hauts-de-France',
    department: 'Nord (59)',
    population: '235 000',
    description: 'Capitale des Flandres et carrefour européen, Lille est une métropole dynamique avec une forte identité locale. Les commerces de proximité y bénéficient d\'une clientèle fidèle, à condition d\'être visibles sur Google Maps.',
    localBusinesses: '40 000+',
    mapCenter: { lat: 50.6292, lng: 3.0573 },
    keyNeighborhoods: ['Vieux-Lille', 'Wazemmes', 'Euralille', 'Vauban', 'République'],
    typicalSearches: ['restaurant lille', 'dentiste lille', 'plombier lille', 'coiffeur vieux-lille'],
  },
  {
    slug: 'rennes',
    name: 'Rennes',
    region: 'Bretagne',
    department: 'Ille-et-Vilaine (35)',
    population: '220 000',
    description: 'Rennes est le cœur économique de la Bretagne, avec un tissu de PME et de commerces très dense. La ville attire de plus en plus de nouveaux résidents, augmentant la concurrence locale sur Google Maps.',
    localBusinesses: '35 000+',
    mapCenter: { lat: 48.1173, lng: -1.6778 },
    keyNeighborhoods: ['Centre historique', 'Sainte-Anne', 'Thabor', 'Villejean', 'Beaulieu'],
    typicalSearches: ['restaurant rennes', 'dentiste rennes', 'plombier rennes', 'boulangerie rennes'],
  },
  {
    slug: 'reims',
    name: 'Reims',
    region: 'Grand Est',
    department: 'Marne (51)',
    population: '185 000',
    description: 'Ville du champagne et du patrimoine, Reims combine tourisme et dynamisme commercial. Les entreprises locales qui dominent Google Maps captent à la fois les résidents et les visiteurs.',
    localBusinesses: '28 000+',
    mapCenter: { lat: 49.2583, lng: 4.0317 },
    keyNeighborhoods: ['Centre-ville', 'Clairmarais', 'Cernay', 'Jean Jaurès', 'Courlancy'],
    typicalSearches: ['restaurant reims', 'dentiste reims', 'plombier reims', 'cave champagne reims'],
  },
  {
    slug: 'toulon',
    name: 'Toulon',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: 'Var (83)',
    population: '180 000',
    description: 'Premier port militaire français, Toulon est aussi une ville de commerces et de services en pleine mutation. La visibilité sur Google Maps y est un levier décisif pour les entreprises locales.',
    localBusinesses: '25 000+',
    mapCenter: { lat: 43.1242, lng: 5.928 },
    keyNeighborhoods: ['Centre-ville', 'Mourillon', 'Le Port', 'Cap Brun', 'La Seyne-sur-Mer'],
    typicalSearches: ['restaurant toulon', 'dentiste toulon', 'plombier toulon', 'garage toulon'],
  },
  {
    slug: 'grenoble',
    name: 'Grenoble',
    region: 'Auvergne-Rhône-Alpes',
    department: 'Isère (38)',
    population: '160 000',
    description: 'Capitale des Alpes françaises, Grenoble est un hub d\'innovation et de recherche. Les entreprises locales profitent d\'un bassin de population qualifiée qui recherche activement des services sur Google Maps.',
    localBusinesses: '25 000+',
    mapCenter: { lat: 45.1885, lng: 5.7245 },
    keyNeighborhoods: ['Centre-ville', 'Europole', 'Berriat', 'Île Verte', 'Eaux Claires'],
    typicalSearches: ['restaurant grenoble', 'dentiste grenoble', 'plombier grenoble', 'opticien grenoble'],
  },
  {
    slug: 'dijon',
    name: 'Dijon',
    region: 'Bourgogne-Franche-Comté',
    department: 'Côte-d\'Or (21)',
    population: '160 000',
    description: 'Capitale de la Bourgogne et ville gastronomique, Dijon attire gourmands et touristes. Les entreprises locales qui optimisent leur fiche Google captent une clientèle fidèle et des visiteurs réguliers.',
    localBusinesses: '22 000+',
    mapCenter: { lat: 47.322, lng: 5.0415 },
    keyNeighborhoods: ['Centre historique', 'Toison d\'Or', 'Fontaine d\'Ouche', 'Grésilles', 'Université'],
    typicalSearches: ['restaurant dijon', 'dentiste dijon', 'plombier dijon', 'boulangerie dijon'],
  },
  {
    slug: 'angers',
    name: 'Angers',
    region: 'Pays de la Loire',
    department: 'Maine-et-Loire (49)',
    population: '155 000',
    description: 'Angers se distingue par sa qualité de vie et son dynamisme économique. Les commerces locaux bénéficient d\'une clientèle attachée à la proximité, qui utilise massivement Google Maps pour trouver des services.',
    localBusinesses: '20 000+',
    mapCenter: { lat: 47.4784, lng: -0.5632 },
    keyNeighborhoods: ['Centre-ville', 'La Doutre', 'Belle-Beille', 'Monplaisir', 'Saint-Serge'],
    typicalSearches: ['restaurant angers', 'dentiste angers', 'plombier angers', 'coiffeur angers'],
  },
  {
    slug: 'nimes',
    name: 'Nîmes',
    region: 'Occitanie',
    department: 'Gard (30)',
    population: '150 000',
    description: 'Ville romaine par excellence, Nîmes allie patrimoine historique et vitalité commerciale. Les entreprises locales qui se positionnent en tête de Google Maps captent résidents et touristes tout au long de l\'année.',
    localBusinesses: '20 000+',
    mapCenter: { lat: 43.8367, lng: 4.3601 },
    keyNeighborhoods: ['Centre historique', 'Les Arènes', 'Jean Jaurès', 'Costières', 'Ville Active'],
    typicalSearches: ['restaurant nîmes', 'dentiste nîmes', 'plombier nîmes', 'garage nîmes'],
  },
  {
    slug: 'aix-en-provence',
    name: 'Aix-en-Provence',
    region: 'Provence-Alpes-Côte d\'Azur',
    department: 'Bouches-du-Rhône (13)',
    population: '145 000',
    description: 'Ville d\'art et d\'histoire, Aix-en-Provence est un pôle économique majeur du sud de la France. La forte densité de commerces et de professions libérales rend la visibilité sur Google Maps cruciale.',
    localBusinesses: '22 000+',
    mapCenter: { lat: 43.5297, lng: 5.4474 },
    keyNeighborhoods: ['Cours Mirabeau', 'Mazarin', 'Centre historique', 'Les Milles', 'Jas de Bouffan'],
    typicalSearches: ['restaurant aix-en-provence', 'dentiste aix', 'avocat aix-en-provence', 'plombier aix'],
  },
  {
    slug: 'saint-etienne',
    name: 'Saint-Étienne',
    region: 'Auvergne-Rhône-Alpes',
    department: 'Loire (42)',
    population: '175 000',
    description: 'Ville UNESCO du design, Saint-Étienne se réinvente et attire de nouveaux entrepreneurs. Le SEO local y est un levier puissant pour les commerces qui veulent se démarquer dans cette métropole en transformation.',
    localBusinesses: '25 000+',
    mapCenter: { lat: 45.4397, lng: 4.3872 },
    keyNeighborhoods: ['Centre-ville', 'Châteaucreux', 'Bellevue', 'Carnot', 'Bergson'],
    typicalSearches: ['restaurant saint-étienne', 'dentiste saint-étienne', 'plombier saint-étienne', 'garage saint-étienne'],
  },
  {
    slug: 'le-havre',
    name: 'Le Havre',
    region: 'Normandie',
    department: 'Seine-Maritime (76)',
    population: '170 000',
    description: 'Port majeur et ville UNESCO, Le Havre est une métropole normande en pleine renaissance. Les entreprises locales qui investissent dans leur visibilité Google Maps prennent une longueur d\'avance sur la concurrence.',
    localBusinesses: '22 000+',
    mapCenter: { lat: 49.4944, lng: 0.1079 },
    keyNeighborhoods: ['Centre reconstruit', 'Sainte-Adresse', 'Danton', 'Les Halles', 'Perrey'],
    typicalSearches: ['restaurant le havre', 'dentiste le havre', 'plombier le havre', 'garage le havre'],
  },
];

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((city) => city.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((city) => city.slug);
}
